### ISSUE TITLE
Prepare for store

### ISSUE THREAD

**Issue by alexellis** [s1monw1/openfaas-kotlin#1]
Hi Simon, this template would be great in the OpenFaaS Template store

Could you consider the following?

* Adding a README
* Adding examples of how to use both templates with and without dependencies such as OKHttp
* Adding a LICENSE
* Adding a CONTRIBUTING statement / guide

Then send over a PR to openfaas/templates 👍 

What do you think?

Alex

**Comment by s1monw1** [comment]
Hi Alex,

sounds great! I just need some more info. 
   

-  Adding a README + Adding examples of how to use both templates with and without dependencies such as OKHttp
     - READMEs can be found in the specific templates, e.g. https://github.com/s1monw1/openfaas-kotlin/tree/master/template/kotlin - This is based on the java12 template, is more content needed? Do you have an example for me?
-  Adding a LICENSE
   - done
-  Adding a CONTRIBUTING statement / guide
   - done

And also, just to clarify, should both go into the store or the templates repository? Is opening an issue mandatory or should I create a PR directly?

**Comment by alexellis** [comment]
You should have a readme at the root and not in the template folder. Look at how we've done this in the other templates which are listed.

**Comment by alexellis** [comment]
Yes raise your issue and PR, no need to wait for permission :+1:
